<?php

return [
    'roles' => [
        'developer',
        'manager',
        'user',
        'pos_sales',
    ],

    'actions' => [
        'view' => 'View',
        'create' => 'Create',
        'update' => 'Update',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'print' => 'Print',
        'approve' => 'Approve',
        'export' => 'Export',
        'send' => 'Send',
        'receive' => 'Receive',
        'cancel' => 'Cancel',
        'generate' => 'Generate',
        'regenerate' => 'Regenerate',
        'apply' => 'Apply',
        'activate' => 'Activate',
        'deactivate' => 'Deactivate',
    ],

    'modules' => [
        'dashboard' => 'Dashboard',
        'products' => 'Products',
        'main_categories' => 'Main Categories',
        'sub_categories' => 'Sub Categories',
        'purchase_invoices' => 'Purchase Invoices',
        'create_purchase_invoice' => 'Create Purchase Invoice',
        'supplier_payments' => 'Supplier Payments',
        'purchase_returns' => 'Purchase Returns',
        'orders' => 'Online Orders',
        'coupons' => 'Coupons',
        'discounts.manual' => 'Manual Discounts',
        'notifications' => 'Notifications',
        'expenses' => 'Expenses',
        'expense_items' => 'Expense Items',
        'customers' => 'Customers',
        'suppliers' => 'Suppliers',
        'users' => 'Users',
        'branches' => 'Branches',
        'colors' => 'Colors',
        'sizes' => 'Sizes',
        'payment_methods' => 'Payment Methods',
        'shipping_governorates' => 'Shipping Governorates',
        'collections' => 'Collections',
        'pos_system' => 'POS System',
        'sales' => 'Sales Management',
        'sales.return' => 'Sales Returns',
        'stock_movements' => 'Stock Movements',
        'inventory_adjustments' => 'Inventory Adjustments',
        'stock_transfers' => 'Stock Transfers',
        'barcodes' => 'Barcodes',
    ],

    'default_role_permissions' => [
        'user' => [
            'dashboard.view',
            'products.view',
            'main_categories.view',
            'sub_categories.view',
            'customers.view',
            'suppliers.view',
            'purchase_invoices.view',
            'create_purchase_invoice.view',
            'supplier_payments.view',
            'purchase_returns.view',
            'orders.view',
            'coupons.view',
            'notifications.view',
            'expenses.view',
            'expense_items.view',
            'collections.view',
        ],

        'pos_sales' => [
            'pos_system.view',
            'pos_system.create',
            'dashboard.view',
            'products.view',
            'customers.view',
            'customers.create',
            'collections.view',
            'payment_methods.view',
            'sales.view',
            'sales.create',
            'sales.print',
            'discounts.manual.apply',
            'sales.return.create',
            'sales.return.view',
            'stock_movements.view',
        ],
    ],

    'route_permissions' => [
        'dashboard' => 'dashboard.view',
        'branches' => 'branches.view',
        'users' => 'users.view',
        'suppliers' => 'suppliers.view',
        'categories' => 'main_categories.view',
        'subCategories' => 'sub_categories.view',
        'customers' => 'customers.view',
        'expenses_items' => 'expense_items.view',
        'products.create' => 'products.create',
        'colors' => 'colors.view',
        'sizes' => 'sizes.view',
        'payment_methods' => 'payment_methods.view',
        'shipping' => 'shipping_governorates.view',
        'all_collections' => 'collections.view',
        'pos_system' => 'pos_system.view',
        'products.edit' => 'products.update',
        'products' => 'products.view',
        'expenses' => 'expenses.view',
        'purchaseInvoices' => 'purchase_invoices.view',
        'createpurchaseInvoices' => 'create_purchase_invoice.create',
        'supplier-payments.index' => 'supplier_payments.view',
        'supplier-payments.create' => 'supplier_payments.create',
        'supplier-payments.show' => 'supplier_payments.view',
        'supplier-payments.print' => 'supplier_payments.print',
        'supplier-ledger.index' => 'supplier_payments.view',
        'supplier-ledger.print' => 'supplier_payments.print',
        'purchaseInvoices.show' => 'purchase_invoices.view',
        'purchase-returns.index' => 'purchase_returns.view',
        'purchase-returns.create' => 'purchase_returns.create',
        'purchase-returns.show' => 'purchase_returns.view',
        'purchase-returns.print' => 'purchase_returns.print',
        'orders' => 'orders.view',
        'coupons.index' => 'coupons.view',
        'sales.index' => 'sales.view',
        'sales.show' => 'sales.view',
        'sales.edit' => 'sales.edit',
        'sales.returns' => 'sales.return.view',
        'sales.reports' => 'sales.view',
        'sales.print' => 'sales.print',
        'sales.returns.print' => 'sales.print',
        'stock-movements.index' => 'stock_movements.view',
        'inventory-adjustments.index' => 'inventory_adjustments.view',
        'stock-transfers.index' => 'stock_transfers.view',
        'stock-transfers.print' => 'stock_transfers.print',
        'barcodes.index' => 'barcodes.view',
        'barcodes.print' => 'barcodes.print',
        'admin.notifications' => 'notifications.view',
        'roles-permissions.index' => 'users.update',
        'user-roles.index' => 'users.update',
        'roles.index' => 'users.update',
    ],
];
